import '../../../styles/globals.css'
import type { Metadata } from 'next'
import Header from 'components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className="max-w-screen-md px-6 mx-auto">
          <Header />
          <main className="container py-10 mx-auto">{children}</main>
        </div>
      </body>
    </html>
  )
}
